@startuml "DiagramaComponentes"

title "Diagrama de Componentes"

skinparam defaultTextAlignment center

skinparam node {
    borderColor Black
    backgroundColor whitesmoke
}

package "Web Site" {
    [SPA\n<<Angular>>] as WebSite
    [Nebular\n<<Angular UI Kit>>] as Nebular
}


interface "Open Search" as SearchInterface

[Message Broker\n<<Kafka>>] as Kafka

node "Amazon\nOpenSearch " as OpenSearch
node "AWS Cognito\n<<OAuth e JWT>>" as Cognito

database StoreDB <<MongoDB>> as StoreDB
database MetricDB <<MongoDB>> as MetricDB


[Api Gateway] as ApiGateway

package "Search Service" {
    [Spring Boot\n<<Rest API>>] as SearchService
    [Offer Core\n<<Library>>] as SSCoreLibray

    SearchService -down- SearchInterface
    SearchService <..down.. Kafka : Consume Create/Update Offer
    SearchInterface )-down- OpenSearch
    SearchService -left-> SSCoreLibray : Use
}

package "Store Service" {
    [Spring Boot\n<<Rest API>>] as StoreService
    interface "Spring Data" as StorePersistence
    [Offer Core\n<<Library>>] as StoreCoreLibray

    StoreService --> StoreCoreLibray
    StoreService <. Kafka : Consume Update Metrics
    StoreService -left-> StorePersistence
    StorePersistence .left.> StoreDB
}

package "Metric Service" {
    [Spring Boot\n<<Rest API>>] as MetricService
    interface "Spring Data" as MetricPersistence
    [Offer Core\n<<Library>>] as MetricCoreLibray

    MetricService --> MetricCoreLibray
    MetricService .> Kafka : "Publish Update Metrics"
    MetricService -right-> MetricPersistence
    MetricPersistence .right.> MetricDB
}

ApiGateway ...> StoreService : HTTP
ApiGateway .right.> MetricService : HTTP
ApiGateway ...> SearchService : HTTP

WebSite .down.> ApiGateway : \t\rUse
WebSite ..right..> Cognito : Use
WebSite ..left..> Nebular : Use


' StoreService ..> Kafka : Use
' MetricService ...> Kafka : Use


' StoreService ...> StoreDB : Use
' MetricService ..right..> MetricDB : Use

' interface HTTP as HttpInterface

note top of WebSite
    Componente utilizado para gerar
    conteúdo HTML dos módulos
    do sistema de forma responsiva
end note

' note right of ApiGateway
'     Api Gateway utilizado
'     para expor serviços da
'     aplicação via API
' end note

note right of OpenSearch
    É um serviço da Amazon
    para realizar pesquisa em grande
    volume de dados
end note

note bottom of Kafka
    Broker de mensageria
    utilizado para publicação
    e consumo de mensagens
    entre os serviços
end note


@enduml