@startuml "DiagramaComponentes"

title "Diagrama de Componentes"

skinparam defaultTextAlignment center

skinparam node {
  borderColor Black
  backgroundColor whitesmoke
}

[Aplicação Web\n<<Angular>>] as WebSite
[Api Gateway] as ApiGateway

[SearchService\n<<Spring Boot>>] as SearchService
[StoreService\n<<Spring Boot>>] as StoreService
[MetricService\n<<Spring Boot>>] as MetricService

[Message Broker\n<<Kafka>>] as Kafka

node "Amazon\nOpenSearch " as OpenSearch
node "AWS Cognito\n<<OAuth e JWT>>" as Cognito

database StoreDB <<MongoDB>> as StoreDB
database MetricDB <<MongoDB>> as MetricDB


' interface HTTP as HttpInterface

note top of WebSite
    Componente utilizado para gerar
    conteúdo HTML dos módulos
    do sistema de forma responsiva  
end note

note left of ApiGateway
    Api Gateway utilizado
    para expor serviços da
    aplicação via API
end note

note top of OpenSearch
    É um serviço da Amazon
    para realizar pesquisa em grande
    volume de dados
end note

note right of Kafka
    Broker de mensageria
    utilizado para publicação
    e consumo de mensagens
    entre os serviços
end note

WebSite ..> ApiGateway : \t\rUse
WebSite ..left..> Cognito : Use

ApiGateway ..> StoreService : Use
ApiGateway ....> SearchService : Use
ApiGateway ..right..> MetricService : Use


StoreService ..> Kafka : Use
MetricService ...> Kafka : Use

SearchService ..left..> OpenSearch : Use
StoreService ...> StoreDB : Use
MetricService ..right..> MetricDB : Use


@enduml