name: PlantUML
on:
  push:
    paths:
      - '**.puml'
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ts-graphviz/setup-graphviz@v1
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)"
      - name: Get changed UML files
        id: getfile2
        run: |
          git diff-tree -r --no-commit-id --summary ${{ github.sha }} \
          | awk -F' ' '{
            # ensure we are not trying to process deleted files
            # only process puml files
            # do not try to process our theme or custom config
            if ( $1 !~ /^delete$/ && $4 ~ /\.puml$/ && $4 !~ /(theme|config)\.puml$/ )
            {
              # only print the file name and strip newlines for spaces
              printf "::set-output name=files::" "%s ", $4
            }
          }
          END { print "" } # ensure we do print a newline at the end
          '
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile2.outputs.files }}
      - run: wget --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
      - run: java -jar plantuml.jar -v -tpng ${{ steps.getfile.outputs.files }}
      - run: java -jar plantuml.jar -v -tpng ${{ steps.getfile2.outputs.files }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'generate PNG for PlantUML'
          add: '*.png'
          push: false
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}