name: PlantUML
on:
  push:
    paths:
      - '**.puml'
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ts-graphviz/setup-graphviz@v1
      # - name: Get changed UML files
      #   id: getfile
      #   run: |
      #     echo '::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)'
      - name: Get changed UML files
        id: getfile
        run: |
          echo '::set-output name=files::$(ls | grep '.puml' | xargs)'
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - run: wget --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
      - run: java -jar plantuml.jar -v -tpng ${{ steps.getfile.outputs.files }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'generate PNG for PlantUML'
          add: '*.png'
          push: false
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}