name: PlantUML
on:
  push:
    paths:
      - '**.puml'
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ts-graphviz/setup-graphviz@v1
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - run: wget --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
      - run: java -jar plantuml.jar -v -tpng ${{ steps.getfile.outputs.files }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'generate PNG for PlantUML'
          add: '*.png'
          push: false
      
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "Nelson Rodrigues"
          commit_user_email: "nrsjnet@gmail.com"
          commit_author: "Usuário <nrsjnet@gmail.com>"
          commit_message: "Gerar SVG e PNG imagens dos diagramas PlantUML" 
          branch: ${{ github.head_ref }}
